name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Version Tag (vX.X.X)"
        type: string
        required: true
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:       
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          stable: true          
      - name: Cross Build
        run: |
          brew install filosottile/musl-cross/musl-cross
          brew install libx11
          ln -s /opt/X11/include/X11 /usr/local/include/X11
          make all
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ github.event.inputs.tag }}
          message: "create tag"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release & Assets
        uses: Hs1r1us/Release-AIO@v1.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:  ${{ github.event.inputs.tag }} 
          release_name: imgbb-cli ${{ github.event.inputs.tag }} 
          asset_files: bin/       
          
